---
- name: Install Dependencies
  hosts: all
  become: yes
  remote_user: ubuntu
  # vars:
  #   ansible_ssh_private_key_file: /home/andres/Documents/ansible/key_pair.pem
  #   ansible_ssh_user: "ubuntu"

  roles:
    - packages
    - docker
    - minikube