apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      volumes:
      - name: mysql
        emptyDir: {}
      containers:
      - name: myapp
        image: andresdckr/devopsfinalproject-todo:2.0 # {{TAG}}
        ports:
        - name: http-port
          containerPort: 3000
        env:
        - name: MYSQL_DB
          value: "todos"
        - name: MYSQL_USER
          value: "root"
        - name: MYSQL_PASSWORD
          value: "123456"
        - name: MYSQL_HOST
          value: "127.0.0.1"
      - name: db
        image: mysql:8.0
        ports:
        - name: mysql-port
          containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "123456"
        - name: MYSQL_DATABASE
          value: "todos"
        volumeMounts:
        - name: mysql
          mountPath: /var/lib/mysql