---
- name: Install Docker
  block:
    - name: Updating package cache
      apt:
        update_cache: yes
        
    - name: Installing Docker
      apt:
        name: docker.io
        state: present
      when: ansible_facts.packages['docker.io'] is not defined

    - name: Adding Docker to the group
      user:
        name: "{{ item }}"
        groups: docker
        append: yes
      loop:
        - ubuntu
      when: ansible_os_family == 'Debian'

    - name: Apply group membership
      shell: newgrp docker
      when: ansible_os_family == 'Debian'


    - name: Restarting docker
      systemd:
        name: docker
        state: restarted
      when: ansible_os_family == 'Debian'

    - name: Docker sock permissions
      file:
        path: /var/run/docker.sock
        mode: '0777'
      when: ansible_os_family == 'Debian'